// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package config

import (
	defaults "github.com/creasty/defaults"
	helpers "github.com/ecordell/optgen/helpers"
)

type ConfigurationOption func(c *Configuration)

// NewConfigurationWithOptions creates a new Configuration with the passed in options set
func NewConfigurationWithOptions(opts ...ConfigurationOption) *Configuration {
	c := &Configuration{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// NewConfigurationWithOptionsAndDefaults creates a new Configuration with the passed in options set starting from the defaults
func NewConfigurationWithOptionsAndDefaults(opts ...ConfigurationOption) *Configuration {
	c := &Configuration{}
	defaults.MustSet(c)
	for _, o := range opts {
		o(c)
	}
	return c
}

// ToOption returns a new ConfigurationOption that sets the values from the passed in Configuration
func (c *Configuration) ToOption() ConfigurationOption {
	return func(to *Configuration) {
		to.ServerMode = c.ServerMode
		to.Mode = c.Mode
		to.HTTPPort = c.HTTPPort
		to.StaticsFolder = c.StaticsFolder
		to.DataFolder = c.DataFolder
		to.ConsoleURL = c.ConsoleURL
		to.Auth = c.Auth
		to.LogFormat = c.LogFormat
		to.LogLevel = c.LogLevel
	}
}

// DebugMap returns a map form of Configuration for debugging
func (c *Configuration) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["ServerMode"] = helpers.DebugValue(c.ServerMode, false)
	debugMap["Mode"] = helpers.DebugValue(c.Mode, false)
	debugMap["HTTPPort"] = helpers.DebugValue(c.HTTPPort, false)
	debugMap["StaticsFolder"] = helpers.DebugValue(c.StaticsFolder, false)
	debugMap["DataFolder"] = helpers.DebugValue(c.DataFolder, false)
	debugMap["ConsoleURL"] = helpers.DebugValue(c.ConsoleURL, false)
	debugMap["Auth"] = helpers.DebugValue(c.Auth, false)
	debugMap["LogFormat"] = helpers.DebugValue(c.LogFormat, false)
	debugMap["LogLevel"] = helpers.DebugValue(c.LogLevel, false)
	return debugMap
}

// ConfigurationWithOptions configures an existing Configuration with the passed in options set
func ConfigurationWithOptions(c *Configuration, opts ...ConfigurationOption) *Configuration {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithOptions configures the receiver Configuration with the passed in options set
func (c *Configuration) WithOptions(opts ...ConfigurationOption) *Configuration {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithServerMode returns an option that can set ServerMode on a Configuration
func WithServerMode(serverMode string) ConfigurationOption {
	return func(c *Configuration) {
		c.ServerMode = serverMode
	}
}

// WithMode returns an option that can set Mode on a Configuration
func WithMode(mode string) ConfigurationOption {
	return func(c *Configuration) {
		c.Mode = mode
	}
}

// WithHTTPPort returns an option that can set HTTPPort on a Configuration
func WithHTTPPort(hTTPPort int) ConfigurationOption {
	return func(c *Configuration) {
		c.HTTPPort = hTTPPort
	}
}

// WithStaticsFolder returns an option that can set StaticsFolder on a Configuration
func WithStaticsFolder(staticsFolder string) ConfigurationOption {
	return func(c *Configuration) {
		c.StaticsFolder = staticsFolder
	}
}

// WithDataFolder returns an option that can set DataFolder on a Configuration
func WithDataFolder(dataFolder string) ConfigurationOption {
	return func(c *Configuration) {
		c.DataFolder = dataFolder
	}
}

// WithConsoleURL returns an option that can set ConsoleURL on a Configuration
func WithConsoleURL(consoleURL string) ConfigurationOption {
	return func(c *Configuration) {
		c.ConsoleURL = consoleURL
	}
}

// WithAuth returns an option that can set Auth on a Configuration
func WithAuth(auth Authentication) ConfigurationOption {
	return func(c *Configuration) {
		c.Auth = auth
	}
}

// WithLogFormat returns an option that can set LogFormat on a Configuration
func WithLogFormat(logFormat string) ConfigurationOption {
	return func(c *Configuration) {
		c.LogFormat = logFormat
	}
}

// WithLogLevel returns an option that can set LogLevel on a Configuration
func WithLogLevel(logLevel string) ConfigurationOption {
	return func(c *Configuration) {
		c.LogLevel = logLevel
	}
}
