// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

//go:build tools
// +build tools

package tools

// tool dependencies
import (
	_ "github.com/ecordell/optgen"
)

// If you want to use tools, please run the following command:
//  go generate ./tools.go
//
//go:generate go build -v -o=./bin/gex github.com/izumin5210/gex/cmd/gex
//go:generate go build -v -o=./bin/gen github.com/smallnest/gen
